/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.jme3.gde.templates.gradledesktop;

import com.jme3.gde.templates.gradledesktop.options.JMEVersion;
import com.jme3.gde.templates.gradledesktop.options.LWJGLVersion;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.JComboBox;
import javax.swing.JEditorPane;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTextArea;
import javax.swing.JTextPane;
import javax.swing.LayoutStyle;
import javax.swing.event.HyperlinkEvent;
import javax.swing.event.HyperlinkListener;
import org.openide.WizardDescriptor;
import org.openide.awt.Mnemonics;
import org.openide.util.Exceptions;
import org.openide.util.NbBundle;

/**
 *
 * @author peedeeboy
 */
public class GradleDesktopGameJMEVersionPanelVisual extends JPanel {

    private final GradleDesktopGameJMEVersionPanel panel;
    private static final Logger LOGGER = Logger.getLogger(GradleDesktopGameJMEVersionPanel.class.getName());

    /**
     * Creates new form GradleDesktopGameJMEVersion
     */
    public GradleDesktopGameJMEVersionPanelVisual(GradleDesktopGameJMEVersionPanel panel) {
        initComponents();
        additionalComponentConfiguration();

        loadPatchNotes();
        updateLWJGLdescription();
        this.panel = panel;
    }

    private void additionalComponentConfiguration() {
        // Set the JME Version text pane to use system fonts so it displays correctly
        // on dark themes such as DarkMonkey
        jmeVersionDescriptionTextPane.putClientProperty(JEditorPane.HONOR_DISPLAY_PROPERTIES, Boolean.TRUE);

        // Set a URL handler on the JME Version text pane so patch notes will open
        // in browser
        jmeVersionDescriptionTextPane.addHyperlinkListener(new HyperlinkListener() {
            public void hyperlinkUpdate(HyperlinkEvent e) {
                if (e.getEventType() == HyperlinkEvent.EventType.ACTIVATED) {
                    if(Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(e.getURL().toURI());
                        } catch (URISyntaxException ex) {
                            LOGGER.warning("Badly formatted URL: " + e.toString());
                        } catch (IOException ex) {
                            LOGGER.warning("Could not open browser: " + e.toString());
                        }                     
                    }
                }
            }
        });
    }

    private void loadPatchNotes() {
        JMEVersion jmeVersionSelected = (JMEVersion) jmeVersionComboBox.getSelectedItem();
        try {
            URL patchNotesURL = GradleDesktopGameJMEVersionPanelVisual.class.getResource(jmeVersionSelected.getPatchNotesPath());
            jmeVersionDescriptionTextPane.setPage(patchNotesURL);
        } catch (IOException ex) {
            LOGGER.log(Level.SEVERE, "Could not open patch notes for JME Version: " + jmeVersionSelected.toString());
            jmeVersionDescriptionTextPane.setText("");
            Exceptions.printStackTrace(ex);
        }
    }

    private void updateLWJGLdescription() {
        LWJGLVersion lwjglVersion = (LWJGLVersion) lwjglComboBox.getSelectedItem();
        lwjglTextArea.setText(lwjglVersion.getDescription());
    }

    protected void store(WizardDescriptor d) {
        String jmeVersion = jmeVersionComboBox.getSelectedItem().toString();
        LWJGLVersion lwjglVersion = (LWJGLVersion) lwjglComboBox.getSelectedItem();
        String lwjglArtifact = lwjglVersion.getArtifact();

        d.putProperty("jmeVersion", jmeVersion);
        d.putProperty("lwjglArtifact", lwjglArtifact);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jmeVersionLabel = new JLabel();
        jmeVersionComboBox = new JComboBox<>();
        jmeVersionDescriptionScrollPane = new JScrollPane();
        jmeVersionDescriptionTextPane = new JTextPane();
        jSeparator1 = new JSeparator();
        lwjglVersionLabel = new JLabel();
        lwjglComboBox = new JComboBox<>();
        lwjglDescriptionScrollPane = new JScrollPane();
        lwjglTextArea = new JTextArea();

        setPreferredSize(new Dimension(280, 360));

        jmeVersionLabel.setLabelFor(jmeVersionComboBox);
        Mnemonics.setLocalizedText(jmeVersionLabel, NbBundle.getMessage(GradleDesktopGameJMEVersionPanelVisual.class, "GradleDesktopGameJMEVersionPanelVisual.jmeVersionLabel.text")); // NOI18N

        jmeVersionComboBox.setModel(new DefaultComboBoxModel(JMEVersion.values()));
        jmeVersionComboBox.setMaximumSize(new Dimension(100, 25));
        jmeVersionComboBox.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jmeVersionComboBoxActionPerformed(evt);
            }
        });

        jmeVersionDescriptionTextPane.setEditable(false);
        jmeVersionDescriptionTextPane.setContentType("text/html"); // NOI18N
        jmeVersionDescriptionTextPane.setText(NbBundle.getMessage(GradleDesktopGameJMEVersionPanelVisual.class, "GradleDesktopGameJMEVersionPanelVisual.jmeVersionDescriptionTextPane.text")); // NOI18N
        try {
            jmeVersionDescriptionTextPane.setPage(GradleDesktopGameJMEVersionPanelVisual.class.getResource("/com/jme3/gde/templates/files/patchnotes/341-stable.html"));
        } catch (IOException e1) {
            e1.printStackTrace();
        }
        jmeVersionDescriptionScrollPane.setViewportView(jmeVersionDescriptionTextPane);

        lwjglVersionLabel.setLabelFor(lwjglComboBox);
        Mnemonics.setLocalizedText(lwjglVersionLabel, NbBundle.getMessage(GradleDesktopGameJMEVersionPanelVisual.class, "GradleDesktopGameJMEVersionPanelVisual.lwjglVersionLabel.text")); // NOI18N

        lwjglComboBox.setModel(new DefaultComboBoxModel(LWJGLVersion.values()));
        lwjglComboBox.setMaximumSize(new Dimension(100, 25));
        lwjglComboBox.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                lwjglComboBoxActionPerformed(evt);
            }
        });

        lwjglTextArea.setEditable(false);
        lwjglTextArea.setColumns(20);
        lwjglTextArea.setLineWrap(true);
        lwjglTextArea.setRows(3);
        lwjglTextArea.setWrapStyleWord(true);
        lwjglDescriptionScrollPane.setViewportView(lwjglTextArea);

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lwjglDescriptionScrollPane)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jmeVersionDescriptionScrollPane, GroupLayout.Alignment.TRAILING)
                            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jmeVersionLabel)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jmeVersionComboBox, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, GroupLayout.Alignment.TRAILING))
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lwjglVersionLabel)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lwjglComboBox, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jmeVersionLabel)
                    .addComponent(jmeVersionComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmeVersionDescriptionScrollPane, GroupLayout.PREFERRED_SIZE, 192, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lwjglVersionLabel)
                    .addComponent(lwjglComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(lwjglDescriptionScrollPane, GroupLayout.PREFERRED_SIZE, 70, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lwjglComboBoxActionPerformed(ActionEvent evt) {//GEN-FIRST:event_lwjglComboBoxActionPerformed
        updateLWJGLdescription();
    }//GEN-LAST:event_lwjglComboBoxActionPerformed

    private void jmeVersionComboBoxActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jmeVersionComboBoxActionPerformed
        loadPatchNotes();
    }//GEN-LAST:event_jmeVersionComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    JSeparator jSeparator1;
    JComboBox<String> jmeVersionComboBox;
    JScrollPane jmeVersionDescriptionScrollPane;
    JTextPane jmeVersionDescriptionTextPane;
    JLabel jmeVersionLabel;
    JComboBox<String> lwjglComboBox;
    JScrollPane lwjglDescriptionScrollPane;
    JTextArea lwjglTextArea;
    JLabel lwjglVersionLabel;
    // End of variables declaration//GEN-END:variables

}
